from tkinter import *

Commands = list()
Functions = list()
Commands.append('help')
Functions.append('-Shows a list of commands')
Commands.append('skip')
Functions.append('-Toggles stuttering off')
Commands.append('play')
Functions.append('-Toggles stuttering on')
Commands.append('look around')
Functions.append('-Tells you what is in the room')
Commands.append('show inventory')
Functions.append('-Tells you what is in your inventory')
Commands.append('search [object]')
Functions.append('-Tells you what is in a container')
Commands.append('take [item]')
Functions.append('-Puts an item in your inventory')
Commands.append('take all')
Functions.append('-Puts all available items in your inventory')
Commands.append('use [item]')
Functions.append('-Lets you excersise the funtionality of an item')
Commands.append('leave [place]')
Functions.append('-Lets you leave where you are')
Commands.append('go through [direction] port')
Functions.append('-Travel into adjacent modules')
Commands.append('drop [item]')
Functions.append('-Removes an item from your inventory')
Commands.append('quit')
Functions.append('-Ends the game')
Commands.append('WARNING:')
Functions.append('Parsing is not yet implemented, so enter commands as they appear here.')

#make window
helpw = Tk()
helpw.title('help')
helpc = Canvas(helpw, height = (len(Commands)*20)+20, width = 650)
helpc.pack()

Text = list()
for i in range (len(Commands)):
	Text.append(helpc.create_text(325, (i*20)+20, text=Commands[i] + ' ' + Functions[i]))
print('wut')
